//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffSystem.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private System.DateTime DoBField;
        
        private System.DateTime JoinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        private bool AdminField;
        
        private bool EmployedField;
        
        private bool StatusField;
        
        private int EntitlementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DoB {
            get {
                return this.DoBField;
            }
            set {
                if ((this.DoBField.Equals(value) != true)) {
                    this.DoBField = value;
                    this.RaisePropertyChanged("DoB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime JoinDate {
            get {
                return this.JoinDateField;
            }
            set {
                if ((this.JoinDateField.Equals(value) != true)) {
                    this.JoinDateField = value;
                    this.RaisePropertyChanged("JoinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Employed {
            get {
                return this.EmployedField;
            }
            set {
                if ((this.EmployedField.Equals(value) != true)) {
                    this.EmployedField = value;
                    this.RaisePropertyChanged("Employed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Entitlement {
            get {
                return this.EntitlementField;
            }
            set {
                if ((this.EntitlementField.Equals(value) != true)) {
                    this.EntitlementField = value;
                    this.RaisePropertyChanged("Entitlement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Holidays", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Holidays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffSystem.ServiceReference.Employee StaffField;
        
        private System.DateTime StartField;
        
        private System.DateTime EndField;
        
        private bool PendingField;
        
        private bool ApprovedField;
        
        private bool CanceledField;
        
        private int PeakTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffSystem.ServiceReference.ArrayOfString ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public StaffSystem.ServiceReference.Employee Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Pending {
            get {
                return this.PendingField;
            }
            set {
                if ((this.PendingField.Equals(value) != true)) {
                    this.PendingField = value;
                    this.RaisePropertyChanged("Pending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Approved {
            get {
                return this.ApprovedField;
            }
            set {
                if ((this.ApprovedField.Equals(value) != true)) {
                    this.ApprovedField = value;
                    this.RaisePropertyChanged("Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Canceled {
            get {
                return this.CanceledField;
            }
            set {
                if ((this.CanceledField.Equals(value) != true)) {
                    this.CanceledField = value;
                    this.RaisePropertyChanged("Canceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PeakTotal {
            get {
                return this.PeakTotalField;
            }
            set {
                if ((this.PeakTotalField.Equals(value) != true)) {
                    this.PeakTotalField = value;
                    this.RaisePropertyChanged("PeakTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public StaffSystem.ServiceReference.ArrayOfString Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapacityDates", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CapacityDates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int MinimumField;
        
        private System.DateTime StartField;
        
        private System.DateTime EndField;
        
        private bool AnnualField;
        
        private bool PeakField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Minimum {
            get {
                return this.MinimumField;
            }
            set {
                if ((this.MinimumField.Equals(value) != true)) {
                    this.MinimumField = value;
                    this.RaisePropertyChanged("Minimum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Annual {
            get {
                return this.AnnualField;
            }
            set {
                if ((this.AnnualField.Equals(value) != true)) {
                    this.AnnualField = value;
                    this.RaisePropertyChanged("Annual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Peak {
            get {
                return this.PeakField;
            }
            set {
                if ((this.PeakField.Equals(value) != true)) {
                    this.PeakField = value;
                    this.RaisePropertyChanged("Peak");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        StaffSystem.ServiceReference.CheckLoginResponse CheckLogin(StaffSystem.ServiceReference.CheckLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.CheckLoginResponse> CheckLoginAsync(StaffSystem.ServiceReference.CheckLoginRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaff", ReplyAction="*")]
        StaffSystem.ServiceReference.GetStaffResponse GetStaff(StaffSystem.ServiceReference.GetStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetStaffResponse> GetStaffAsync(StaffSystem.ServiceReference.GetStaffRequest request);
        
        // CODEGEN: Generating message contract since element name GetManagementResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManagement", ReplyAction="*")]
        StaffSystem.ServiceReference.GetManagementResponse GetManagement(StaffSystem.ServiceReference.GetManagementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManagement", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetManagementResponse> GetManagementAsync(StaffSystem.ServiceReference.GetManagementRequest request);
        
        // CODEGEN: Generating message contract since element name GetSeniorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeniors", ReplyAction="*")]
        StaffSystem.ServiceReference.GetSeniorsResponse GetSeniors(StaffSystem.ServiceReference.GetSeniorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeniors", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetSeniorsResponse> GetSeniorsAsync(StaffSystem.ServiceReference.GetSeniorsRequest request);
        
        // CODEGEN: Generating message contract since element name role from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalRoleNum", ReplyAction="*")]
        StaffSystem.ServiceReference.GetTotalRoleNumResponse GetTotalRoleNum(StaffSystem.ServiceReference.GetTotalRoleNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalRoleNum", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalRoleNumResponse> GetTotalRoleNumAsync(StaffSystem.ServiceReference.GetTotalRoleNumRequest request);
        
        // CODEGEN: Generating message contract since element name department from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalDepartmentNum", ReplyAction="*")]
        StaffSystem.ServiceReference.GetTotalDepartmentNumResponse GetTotalDepartmentNum(StaffSystem.ServiceReference.GetTotalDepartmentNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalDepartmentNum", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalDepartmentNumResponse> GetTotalDepartmentNumAsync(StaffSystem.ServiceReference.GetTotalDepartmentNumRequest request);
        
        // CODEGEN: Generating message contract since element name GetApprovedHolidaysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApprovedHolidays", ReplyAction="*")]
        StaffSystem.ServiceReference.GetApprovedHolidaysResponse GetApprovedHolidays(StaffSystem.ServiceReference.GetApprovedHolidaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetApprovedHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetApprovedHolidaysResponse> GetApprovedHolidaysAsync(StaffSystem.ServiceReference.GetApprovedHolidaysRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutstandingHolidays", ReplyAction="*")]
        StaffSystem.ServiceReference.GetOutstandingHolidaysResponse GetOutstandingHolidays(StaffSystem.ServiceReference.GetOutstandingHolidaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutstandingHolidays", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetOutstandingHolidaysResponse> GetOutstandingHolidaysAsync(StaffSystem.ServiceReference.GetOutstandingHolidaysRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitBooking", ReplyAction="*")]
        StaffSystem.ServiceReference.SubmitBookingResponse SubmitBooking(StaffSystem.ServiceReference.SubmitBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.SubmitBookingResponse> SubmitBookingAsync(StaffSystem.ServiceReference.SubmitBookingRequest request);
        
        // CODEGEN: Generating message contract since element name DefaultOnDutyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DefaultOnDuty", ReplyAction="*")]
        StaffSystem.ServiceReference.DefaultOnDutyResponse DefaultOnDuty(StaffSystem.ServiceReference.DefaultOnDutyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DefaultOnDuty", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.DefaultOnDutyResponse> DefaultOnDutyAsync(StaffSystem.ServiceReference.DefaultOnDutyRequest request);
        
        // CODEGEN: Generating message contract since element name GetPeriodTimesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPeriodTimes", ReplyAction="*")]
        StaffSystem.ServiceReference.GetPeriodTimesResponse GetPeriodTimes(StaffSystem.ServiceReference.GetPeriodTimesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPeriodTimes", ReplyAction="*")]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetPeriodTimesResponse> GetPeriodTimesAsync(StaffSystem.ServiceReference.GetPeriodTimesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLogin", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.CheckLoginRequestBody Body;
        
        public CheckLoginRequest() {
        }
        
        public CheckLoginRequest(StaffSystem.ServiceReference.CheckLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckLoginRequestBody() {
        }
        
        public CheckLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.CheckLoginResponseBody Body;
        
        public CheckLoginResponse() {
        }
        
        public CheckLoginResponse(StaffSystem.ServiceReference.CheckLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckLoginResult;
        
        public CheckLoginResponseBody() {
        }
        
        public CheckLoginResponseBody(bool CheckLoginResult) {
            this.CheckLoginResult = CheckLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaff", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetStaffRequestBody Body;
        
        public GetStaffRequest() {
        }
        
        public GetStaffRequest(StaffSystem.ServiceReference.GetStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public GetStaffRequestBody() {
        }
        
        public GetStaffRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetStaffResponseBody Body;
        
        public GetStaffResponse() {
        }
        
        public GetStaffResponse(StaffSystem.ServiceReference.GetStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.Employee GetStaffResult;
        
        public GetStaffResponseBody() {
        }
        
        public GetStaffResponseBody(StaffSystem.ServiceReference.Employee GetStaffResult) {
            this.GetStaffResult = GetStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetManagementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetManagement", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetManagementRequestBody Body;
        
        public GetManagementRequest() {
        }
        
        public GetManagementRequest(StaffSystem.ServiceReference.GetManagementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetManagementRequestBody {
        
        public GetManagementRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetManagementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetManagementResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetManagementResponseBody Body;
        
        public GetManagementResponse() {
        }
        
        public GetManagementResponse(StaffSystem.ServiceReference.GetManagementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetManagementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.ArrayOfString GetManagementResult;
        
        public GetManagementResponseBody() {
        }
        
        public GetManagementResponseBody(StaffSystem.ServiceReference.ArrayOfString GetManagementResult) {
            this.GetManagementResult = GetManagementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeniorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeniors", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetSeniorsRequestBody Body;
        
        public GetSeniorsRequest() {
        }
        
        public GetSeniorsRequest(StaffSystem.ServiceReference.GetSeniorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSeniorsRequestBody {
        
        public GetSeniorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeniorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeniorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetSeniorsResponseBody Body;
        
        public GetSeniorsResponse() {
        }
        
        public GetSeniorsResponse(StaffSystem.ServiceReference.GetSeniorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeniorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.ArrayOfString GetSeniorsResult;
        
        public GetSeniorsResponseBody() {
        }
        
        public GetSeniorsResponseBody(StaffSystem.ServiceReference.ArrayOfString GetSeniorsResult) {
            this.GetSeniorsResult = GetSeniorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalRoleNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalRoleNum", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetTotalRoleNumRequestBody Body;
        
        public GetTotalRoleNumRequest() {
        }
        
        public GetTotalRoleNumRequest(StaffSystem.ServiceReference.GetTotalRoleNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalRoleNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string role;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string department;
        
        public GetTotalRoleNumRequestBody() {
        }
        
        public GetTotalRoleNumRequestBody(string role, string department) {
            this.role = role;
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalRoleNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalRoleNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetTotalRoleNumResponseBody Body;
        
        public GetTotalRoleNumResponse() {
        }
        
        public GetTotalRoleNumResponse(StaffSystem.ServiceReference.GetTotalRoleNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalRoleNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalRoleNumResult;
        
        public GetTotalRoleNumResponseBody() {
        }
        
        public GetTotalRoleNumResponseBody(int GetTotalRoleNumResult) {
            this.GetTotalRoleNumResult = GetTotalRoleNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalDepartmentNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalDepartmentNum", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetTotalDepartmentNumRequestBody Body;
        
        public GetTotalDepartmentNumRequest() {
        }
        
        public GetTotalDepartmentNumRequest(StaffSystem.ServiceReference.GetTotalDepartmentNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalDepartmentNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string department;
        
        public GetTotalDepartmentNumRequestBody() {
        }
        
        public GetTotalDepartmentNumRequestBody(string department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalDepartmentNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalDepartmentNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetTotalDepartmentNumResponseBody Body;
        
        public GetTotalDepartmentNumResponse() {
        }
        
        public GetTotalDepartmentNumResponse(StaffSystem.ServiceReference.GetTotalDepartmentNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalDepartmentNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalDepartmentNumResult;
        
        public GetTotalDepartmentNumResponseBody() {
        }
        
        public GetTotalDepartmentNumResponseBody(int GetTotalDepartmentNumResult) {
            this.GetTotalDepartmentNumResult = GetTotalDepartmentNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApprovedHolidaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApprovedHolidays", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetApprovedHolidaysRequestBody Body;
        
        public GetApprovedHolidaysRequest() {
        }
        
        public GetApprovedHolidaysRequest(StaffSystem.ServiceReference.GetApprovedHolidaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetApprovedHolidaysRequestBody {
        
        public GetApprovedHolidaysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApprovedHolidaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApprovedHolidaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetApprovedHolidaysResponseBody Body;
        
        public GetApprovedHolidaysResponse() {
        }
        
        public GetApprovedHolidaysResponse(StaffSystem.ServiceReference.GetApprovedHolidaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetApprovedHolidaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.Holidays[] GetApprovedHolidaysResult;
        
        public GetApprovedHolidaysResponseBody() {
        }
        
        public GetApprovedHolidaysResponseBody(StaffSystem.ServiceReference.Holidays[] GetApprovedHolidaysResult) {
            this.GetApprovedHolidaysResult = GetApprovedHolidaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutstandingHolidaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutstandingHolidays", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetOutstandingHolidaysRequestBody Body;
        
        public GetOutstandingHolidaysRequest() {
        }
        
        public GetOutstandingHolidaysRequest(StaffSystem.ServiceReference.GetOutstandingHolidaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOutstandingHolidaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public GetOutstandingHolidaysRequestBody() {
        }
        
        public GetOutstandingHolidaysRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutstandingHolidaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutstandingHolidaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetOutstandingHolidaysResponseBody Body;
        
        public GetOutstandingHolidaysResponse() {
        }
        
        public GetOutstandingHolidaysResponse(StaffSystem.ServiceReference.GetOutstandingHolidaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOutstandingHolidaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.Holidays[] GetOutstandingHolidaysResult;
        
        public GetOutstandingHolidaysResponseBody() {
        }
        
        public GetOutstandingHolidaysResponseBody(StaffSystem.ServiceReference.Holidays[] GetOutstandingHolidaysResult) {
            this.GetOutstandingHolidaysResult = GetOutstandingHolidaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitBooking", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.SubmitBookingRequestBody Body;
        
        public SubmitBookingRequest() {
        }
        
        public SubmitBookingRequest(StaffSystem.ServiceReference.SubmitBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDate;
        
        public SubmitBookingRequestBody() {
        }
        
        public SubmitBookingRequestBody(string username, System.DateTime startDate, System.DateTime endDate) {
            this.username = username;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.SubmitBookingResponseBody Body;
        
        public SubmitBookingResponse() {
        }
        
        public SubmitBookingResponse(StaffSystem.ServiceReference.SubmitBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SubmitBookingResponseBody {
        
        public SubmitBookingResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultOnDutyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultOnDuty", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.DefaultOnDutyRequestBody Body;
        
        public DefaultOnDutyRequest() {
        }
        
        public DefaultOnDutyRequest(StaffSystem.ServiceReference.DefaultOnDutyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DefaultOnDutyRequestBody {
        
        public DefaultOnDutyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefaultOnDutyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DefaultOnDutyResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.DefaultOnDutyResponseBody Body;
        
        public DefaultOnDutyResponse() {
        }
        
        public DefaultOnDutyResponse(StaffSystem.ServiceReference.DefaultOnDutyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DefaultOnDutyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.CapacityDates DefaultOnDutyResult;
        
        public DefaultOnDutyResponseBody() {
        }
        
        public DefaultOnDutyResponseBody(StaffSystem.ServiceReference.CapacityDates DefaultOnDutyResult) {
            this.DefaultOnDutyResult = DefaultOnDutyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPeriodTimesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPeriodTimes", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetPeriodTimesRequestBody Body;
        
        public GetPeriodTimesRequest() {
        }
        
        public GetPeriodTimesRequest(StaffSystem.ServiceReference.GetPeriodTimesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPeriodTimesRequestBody {
        
        public GetPeriodTimesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPeriodTimesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPeriodTimesResponse", Namespace="http://tempuri.org/", Order=0)]
        public StaffSystem.ServiceReference.GetPeriodTimesResponseBody Body;
        
        public GetPeriodTimesResponse() {
        }
        
        public GetPeriodTimesResponse(StaffSystem.ServiceReference.GetPeriodTimesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPeriodTimesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StaffSystem.ServiceReference.CapacityDates[] GetPeriodTimesResult;
        
        public GetPeriodTimesResponseBody() {
        }
        
        public GetPeriodTimesResponseBody(StaffSystem.ServiceReference.CapacityDates[] GetPeriodTimesResult) {
            this.GetPeriodTimesResult = GetPeriodTimesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : StaffSystem.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<StaffSystem.ServiceReference.WebServiceSoap>, StaffSystem.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.CheckLoginResponse StaffSystem.ServiceReference.WebServiceSoap.CheckLogin(StaffSystem.ServiceReference.CheckLoginRequest request) {
            return base.Channel.CheckLogin(request);
        }
        
        public bool CheckLogin(string username, string password) {
            StaffSystem.ServiceReference.CheckLoginRequest inValue = new StaffSystem.ServiceReference.CheckLoginRequest();
            inValue.Body = new StaffSystem.ServiceReference.CheckLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            StaffSystem.ServiceReference.CheckLoginResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).CheckLogin(inValue);
            return retVal.Body.CheckLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.CheckLoginResponse> StaffSystem.ServiceReference.WebServiceSoap.CheckLoginAsync(StaffSystem.ServiceReference.CheckLoginRequest request) {
            return base.Channel.CheckLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.CheckLoginResponse> CheckLoginAsync(string username, string password) {
            StaffSystem.ServiceReference.CheckLoginRequest inValue = new StaffSystem.ServiceReference.CheckLoginRequest();
            inValue.Body = new StaffSystem.ServiceReference.CheckLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).CheckLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetStaffResponse StaffSystem.ServiceReference.WebServiceSoap.GetStaff(StaffSystem.ServiceReference.GetStaffRequest request) {
            return base.Channel.GetStaff(request);
        }
        
        public StaffSystem.ServiceReference.Employee GetStaff(string user) {
            StaffSystem.ServiceReference.GetStaffRequest inValue = new StaffSystem.ServiceReference.GetStaffRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetStaffRequestBody();
            inValue.Body.user = user;
            StaffSystem.ServiceReference.GetStaffResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetStaff(inValue);
            return retVal.Body.GetStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetStaffResponse> StaffSystem.ServiceReference.WebServiceSoap.GetStaffAsync(StaffSystem.ServiceReference.GetStaffRequest request) {
            return base.Channel.GetStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetStaffResponse> GetStaffAsync(string user) {
            StaffSystem.ServiceReference.GetStaffRequest inValue = new StaffSystem.ServiceReference.GetStaffRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetStaffRequestBody();
            inValue.Body.user = user;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetManagementResponse StaffSystem.ServiceReference.WebServiceSoap.GetManagement(StaffSystem.ServiceReference.GetManagementRequest request) {
            return base.Channel.GetManagement(request);
        }
        
        public StaffSystem.ServiceReference.ArrayOfString GetManagement() {
            StaffSystem.ServiceReference.GetManagementRequest inValue = new StaffSystem.ServiceReference.GetManagementRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetManagementRequestBody();
            StaffSystem.ServiceReference.GetManagementResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetManagement(inValue);
            return retVal.Body.GetManagementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetManagementResponse> StaffSystem.ServiceReference.WebServiceSoap.GetManagementAsync(StaffSystem.ServiceReference.GetManagementRequest request) {
            return base.Channel.GetManagementAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetManagementResponse> GetManagementAsync() {
            StaffSystem.ServiceReference.GetManagementRequest inValue = new StaffSystem.ServiceReference.GetManagementRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetManagementRequestBody();
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetManagementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetSeniorsResponse StaffSystem.ServiceReference.WebServiceSoap.GetSeniors(StaffSystem.ServiceReference.GetSeniorsRequest request) {
            return base.Channel.GetSeniors(request);
        }
        
        public StaffSystem.ServiceReference.ArrayOfString GetSeniors() {
            StaffSystem.ServiceReference.GetSeniorsRequest inValue = new StaffSystem.ServiceReference.GetSeniorsRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetSeniorsRequestBody();
            StaffSystem.ServiceReference.GetSeniorsResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetSeniors(inValue);
            return retVal.Body.GetSeniorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetSeniorsResponse> StaffSystem.ServiceReference.WebServiceSoap.GetSeniorsAsync(StaffSystem.ServiceReference.GetSeniorsRequest request) {
            return base.Channel.GetSeniorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetSeniorsResponse> GetSeniorsAsync() {
            StaffSystem.ServiceReference.GetSeniorsRequest inValue = new StaffSystem.ServiceReference.GetSeniorsRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetSeniorsRequestBody();
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetSeniorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetTotalRoleNumResponse StaffSystem.ServiceReference.WebServiceSoap.GetTotalRoleNum(StaffSystem.ServiceReference.GetTotalRoleNumRequest request) {
            return base.Channel.GetTotalRoleNum(request);
        }
        
        public int GetTotalRoleNum(string role, string department) {
            StaffSystem.ServiceReference.GetTotalRoleNumRequest inValue = new StaffSystem.ServiceReference.GetTotalRoleNumRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetTotalRoleNumRequestBody();
            inValue.Body.role = role;
            inValue.Body.department = department;
            StaffSystem.ServiceReference.GetTotalRoleNumResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetTotalRoleNum(inValue);
            return retVal.Body.GetTotalRoleNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalRoleNumResponse> StaffSystem.ServiceReference.WebServiceSoap.GetTotalRoleNumAsync(StaffSystem.ServiceReference.GetTotalRoleNumRequest request) {
            return base.Channel.GetTotalRoleNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalRoleNumResponse> GetTotalRoleNumAsync(string role, string department) {
            StaffSystem.ServiceReference.GetTotalRoleNumRequest inValue = new StaffSystem.ServiceReference.GetTotalRoleNumRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetTotalRoleNumRequestBody();
            inValue.Body.role = role;
            inValue.Body.department = department;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetTotalRoleNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetTotalDepartmentNumResponse StaffSystem.ServiceReference.WebServiceSoap.GetTotalDepartmentNum(StaffSystem.ServiceReference.GetTotalDepartmentNumRequest request) {
            return base.Channel.GetTotalDepartmentNum(request);
        }
        
        public int GetTotalDepartmentNum(string department) {
            StaffSystem.ServiceReference.GetTotalDepartmentNumRequest inValue = new StaffSystem.ServiceReference.GetTotalDepartmentNumRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetTotalDepartmentNumRequestBody();
            inValue.Body.department = department;
            StaffSystem.ServiceReference.GetTotalDepartmentNumResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetTotalDepartmentNum(inValue);
            return retVal.Body.GetTotalDepartmentNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalDepartmentNumResponse> StaffSystem.ServiceReference.WebServiceSoap.GetTotalDepartmentNumAsync(StaffSystem.ServiceReference.GetTotalDepartmentNumRequest request) {
            return base.Channel.GetTotalDepartmentNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetTotalDepartmentNumResponse> GetTotalDepartmentNumAsync(string department) {
            StaffSystem.ServiceReference.GetTotalDepartmentNumRequest inValue = new StaffSystem.ServiceReference.GetTotalDepartmentNumRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetTotalDepartmentNumRequestBody();
            inValue.Body.department = department;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetTotalDepartmentNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetApprovedHolidaysResponse StaffSystem.ServiceReference.WebServiceSoap.GetApprovedHolidays(StaffSystem.ServiceReference.GetApprovedHolidaysRequest request) {
            return base.Channel.GetApprovedHolidays(request);
        }
        
        public StaffSystem.ServiceReference.Holidays[] GetApprovedHolidays() {
            StaffSystem.ServiceReference.GetApprovedHolidaysRequest inValue = new StaffSystem.ServiceReference.GetApprovedHolidaysRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetApprovedHolidaysRequestBody();
            StaffSystem.ServiceReference.GetApprovedHolidaysResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetApprovedHolidays(inValue);
            return retVal.Body.GetApprovedHolidaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetApprovedHolidaysResponse> StaffSystem.ServiceReference.WebServiceSoap.GetApprovedHolidaysAsync(StaffSystem.ServiceReference.GetApprovedHolidaysRequest request) {
            return base.Channel.GetApprovedHolidaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetApprovedHolidaysResponse> GetApprovedHolidaysAsync() {
            StaffSystem.ServiceReference.GetApprovedHolidaysRequest inValue = new StaffSystem.ServiceReference.GetApprovedHolidaysRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetApprovedHolidaysRequestBody();
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetApprovedHolidaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetOutstandingHolidaysResponse StaffSystem.ServiceReference.WebServiceSoap.GetOutstandingHolidays(StaffSystem.ServiceReference.GetOutstandingHolidaysRequest request) {
            return base.Channel.GetOutstandingHolidays(request);
        }
        
        public StaffSystem.ServiceReference.Holidays[] GetOutstandingHolidays(string user) {
            StaffSystem.ServiceReference.GetOutstandingHolidaysRequest inValue = new StaffSystem.ServiceReference.GetOutstandingHolidaysRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetOutstandingHolidaysRequestBody();
            inValue.Body.user = user;
            StaffSystem.ServiceReference.GetOutstandingHolidaysResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetOutstandingHolidays(inValue);
            return retVal.Body.GetOutstandingHolidaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetOutstandingHolidaysResponse> StaffSystem.ServiceReference.WebServiceSoap.GetOutstandingHolidaysAsync(StaffSystem.ServiceReference.GetOutstandingHolidaysRequest request) {
            return base.Channel.GetOutstandingHolidaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetOutstandingHolidaysResponse> GetOutstandingHolidaysAsync(string user) {
            StaffSystem.ServiceReference.GetOutstandingHolidaysRequest inValue = new StaffSystem.ServiceReference.GetOutstandingHolidaysRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetOutstandingHolidaysRequestBody();
            inValue.Body.user = user;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetOutstandingHolidaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.SubmitBookingResponse StaffSystem.ServiceReference.WebServiceSoap.SubmitBooking(StaffSystem.ServiceReference.SubmitBookingRequest request) {
            return base.Channel.SubmitBooking(request);
        }
        
        public void SubmitBooking(string username, System.DateTime startDate, System.DateTime endDate) {
            StaffSystem.ServiceReference.SubmitBookingRequest inValue = new StaffSystem.ServiceReference.SubmitBookingRequest();
            inValue.Body = new StaffSystem.ServiceReference.SubmitBookingRequestBody();
            inValue.Body.username = username;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            StaffSystem.ServiceReference.SubmitBookingResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).SubmitBooking(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.SubmitBookingResponse> StaffSystem.ServiceReference.WebServiceSoap.SubmitBookingAsync(StaffSystem.ServiceReference.SubmitBookingRequest request) {
            return base.Channel.SubmitBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.SubmitBookingResponse> SubmitBookingAsync(string username, System.DateTime startDate, System.DateTime endDate) {
            StaffSystem.ServiceReference.SubmitBookingRequest inValue = new StaffSystem.ServiceReference.SubmitBookingRequest();
            inValue.Body = new StaffSystem.ServiceReference.SubmitBookingRequestBody();
            inValue.Body.username = username;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).SubmitBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.DefaultOnDutyResponse StaffSystem.ServiceReference.WebServiceSoap.DefaultOnDuty(StaffSystem.ServiceReference.DefaultOnDutyRequest request) {
            return base.Channel.DefaultOnDuty(request);
        }
        
        public StaffSystem.ServiceReference.CapacityDates DefaultOnDuty() {
            StaffSystem.ServiceReference.DefaultOnDutyRequest inValue = new StaffSystem.ServiceReference.DefaultOnDutyRequest();
            inValue.Body = new StaffSystem.ServiceReference.DefaultOnDutyRequestBody();
            StaffSystem.ServiceReference.DefaultOnDutyResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).DefaultOnDuty(inValue);
            return retVal.Body.DefaultOnDutyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.DefaultOnDutyResponse> StaffSystem.ServiceReference.WebServiceSoap.DefaultOnDutyAsync(StaffSystem.ServiceReference.DefaultOnDutyRequest request) {
            return base.Channel.DefaultOnDutyAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.DefaultOnDutyResponse> DefaultOnDutyAsync() {
            StaffSystem.ServiceReference.DefaultOnDutyRequest inValue = new StaffSystem.ServiceReference.DefaultOnDutyRequest();
            inValue.Body = new StaffSystem.ServiceReference.DefaultOnDutyRequestBody();
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).DefaultOnDutyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffSystem.ServiceReference.GetPeriodTimesResponse StaffSystem.ServiceReference.WebServiceSoap.GetPeriodTimes(StaffSystem.ServiceReference.GetPeriodTimesRequest request) {
            return base.Channel.GetPeriodTimes(request);
        }
        
        public StaffSystem.ServiceReference.CapacityDates[] GetPeriodTimes() {
            StaffSystem.ServiceReference.GetPeriodTimesRequest inValue = new StaffSystem.ServiceReference.GetPeriodTimesRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetPeriodTimesRequestBody();
            StaffSystem.ServiceReference.GetPeriodTimesResponse retVal = ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetPeriodTimes(inValue);
            return retVal.Body.GetPeriodTimesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetPeriodTimesResponse> StaffSystem.ServiceReference.WebServiceSoap.GetPeriodTimesAsync(StaffSystem.ServiceReference.GetPeriodTimesRequest request) {
            return base.Channel.GetPeriodTimesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StaffSystem.ServiceReference.GetPeriodTimesResponse> GetPeriodTimesAsync() {
            StaffSystem.ServiceReference.GetPeriodTimesRequest inValue = new StaffSystem.ServiceReference.GetPeriodTimesRequest();
            inValue.Body = new StaffSystem.ServiceReference.GetPeriodTimesRequestBody();
            return ((StaffSystem.ServiceReference.WebServiceSoap)(this)).GetPeriodTimesAsync(inValue);
        }
    }
}
