
package Beans;

import BridgePattern.MakeDigital;
import java.awt.BasicStroke;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;


public class DigitalBean extends LayoutBean implements DashboardBean {
    
    /* Declare variables */
    private int digitalLength, digitalHeight;
    private MakeDigital digital;
    
    
    public DigitalBean(int maxValue) {
        this(100, 50, 10, 0, maxValue, 0);
    }
    
    
    public DigitalBean(int length, int height, int padding, int minValue, int maxValue, int value) {
        super(padding, minValue, maxValue, value);
        
        this.digitalLength = length;
        this.digitalHeight = height;
        
        setPreferredSize(new Dimension(digitalLength + (2 * padding), digitalHeight + (2 * padding)));
    }
    
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g; // Creates Graphics object
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setStroke(new BasicStroke(3, BasicStroke.CAP_ROUND, 0));
        
        drawObject(g2); // Draw the digital display
    }
    
    
    /* Draws a seven segment digital display */
    @Override
    public void drawObject(Graphics2D g2) {
        // Creates a digital display
        digital = new MakeDigital(g2, value);
    }
    
    
    /* Get/Set methods */
    @Override
    public int getMaxValue() { return maxValue; }
    
    @Override 
    public int getMinValue() { return minValue; }
    
    @Override
    public int getValue() { return value; }
    
    @Override
    public void setValue(int value) {
        value = value < minValue ? (int) minValue : value; // Stops value exceeding min limit
        value = value > maxValue ? (int) maxValue : value; // Stops value exceeding max limit
        this.value = value;
        
        repaint(); // Redraws the panel
    }
    
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
